// <auto-generated />
namespace OOBS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Second_Face : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Second_Face));
        
        string IMigrationMetadata.Id
        {
            get { return "202204281840403_Second_Face"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
